version: '3.8'

services:
  myflaskapp:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: run.py
    depends_on:
      - db
  database:
    image: mysql:5.7
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myflaskapp
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"  
  